Category.delete_all
Interest.delete_all

entertainment = Category.create(name: "Entertainment")
sport = Category.create(name: "Sport & Wellness")
lifestyle = Category.create(name: "Lifestyle")


climbing = Interest.create(name:"Climbing", category_id: sport.id)
skiing = Interest.create(name:"Skiing", category_id: sport.id)
gym = Interest.create(name:"Gym", category_id: sport.id)
yoga = Interest.create(name:"Yoga", category_id: sport.id)
football = Interest.create(name:"Football", category_id: sport.id)
hiking = Interest.create(name:"Hiking", category_id: sport.id)
swimming = Interest.create(name:"Swimming", category_id: sport.id)


festivals = Interest.create(name:"Festivals", category_id: entertainment.id)
gigs = Interest.create(name:"Concerts & gigs", category_id: entertainment.id)
theatre = Interest.create(name:"Theatre", category_id: entertainment.id)
cinema = Interest.create(name:"Cinema", category_id: entertainment.id)
gallery = Interest.create(name:"Art galleries", category_id: entertainment.id)
museum = Interest.create(name:"Museums", category_id: entertainment.id)
gaming = Interest.create(name:"Gaming", category_id: entertainment.id)
clubbing = Interest.create(name:"Clubbing", category_id: entertainment.id)


fashion = Interest.create(name:"Fashion", category_id: lifestyle.id)
cooking = Interest.create(name:"Cooking",category_id: lifestyle.id)
travel = Interest.create(name:"Travel", category_id: lifestyle.id)
camping = Interest.create(name:"Camping", category_id: lifestyle.id)

dario=User.create(username: "dar_io", first_name:"Dario", last_name:"Spina", age:29, password:"hello", password_confirmation: "hello")
lola=User.create(username: "lo_la", first_name:"Lola", last_name:"Lola", age:29, password:"hello", password_confirmation: "hello")
joe=User.create(username: "jo_e", first_name:"Joe", last_name:"Spina", age:29, password:"hello", password_confirmation: "hello")
ricky=User.create(username: "ric_ky", first_name:"Ricky", last_name:"Spina", age:29, password:"hello", password_confirmation: "hello")
rob=User.create(username: "ro_b", first_name:"Rob", last_name:"Spina", age:29, password:"hello", password_confirmation: "hello")
natasha=User.create(username: "nat_asha", first_name:"Natasha", last_name:"Spina", age:29, password:"hello", password_confirmation: "hello")
mikko=User.create(username: "mi_kko", first_name:"Mikko", last_name:"Spina", age:29, password:"hello", password_confirmation: "hello")
chris=User.create(username: "chr_is", first_name:"Chris", last_name:"Spina", age:29, password:"hello", password_confirmation: "hello")
demany=User.create(username: "de_many", first_name:"Demany", last_name:"Spina", age:29, password:"hello", password_confirmation: "hello")

u1=UserInterest.create(user_id: dario.id, interest_id: climbing.id)
u2=UserInterest.create(user_id: dario.id, interest_id: gigs.id)
u3=UserInterest.create(user_id: dario.id, interest_id: museum.id)
u4=UserInterest.create(user_id: dario.id, interest_id: gaming.id)
u5=UserInterest.create(user_id: lola.id, interest_id: gigs.id)
u6=UserInterest.create(user_id: lola.id, interest_id: museum.id)
u7=UserInterest.create(user_id: lola.id, interest_id: gaming.id)
u8=UserInterest.create(user_id: lola.id, interest_id: theatre.id)
u5=UserInterest.create(user_id: joe.id, interest_id: gigs.id)
u6=UserInterest.create(user_id: joe.id, interest_id: museum.id)
u7=UserInterest.create(user_id: joe.id, interest_id: cooking.id)
u8=UserInterest.create(user_id: ricky.id, interest_id: gigs.id)
u9=UserInterest.create(user_id: ricky.id, interest_id: museum.id)
u10=UserInterest.create(user_id: ricky.id, interest_id: climbing.id)
u11=UserInterest.create(user_id: mikko.id, interest_id: fashion.id)
u12=UserInterest.create(user_id: mikko.id, interest_id: travel.id)
u13=UserInterest.create(user_id: natasha.id, interest_id: fashion.id)
u14=UserInterest.create(user_id: natasha.id, interest_id: gaming.id)
u15=UserInterest.create(user_id: chris.id, interest_id: fashion.id)
u16=UserInterest.create(user_id: chris.id, interest_id: travel.id)
